# Generated by Django 5.2.5 on 2025-08-26 15:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Personne',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('prenom', models.CharField(max_length=100)),
                ('age', models.PositiveIntegerField()),
                ('lieu_residence', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Livre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=200)),
                ('theme', models.CharField(max_length=100)),
                ('auteur', models.CharField(max_length=100)),
                ('note', models.DecimalField(decimal_places=1, max_digits=3)),
                ('disponible', models.BooleanField(default=True)),
                ('personne', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='biblio.personne')),
            ],
        ),
    ]
