# Generated by Django 5.2.5 on 2025-08-26 15:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biblio', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='livre',
            name='personne',
        ),
        migrations.AddField(
            model_name='personne',
            name='livre_emprunte',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='emprunte_par', to='biblio.livre'),
        ),
    ]
