# Generated by Django 5.2.5 on 2025-08-27 08:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biblio', '0002_remove_livre_personne_personne_livre_emprunte'),
    ]

    operations = [
        migrations.CreateModel(
            name='Auteur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=150)),
                ('date_naissance', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='livre',
            name='disponible',
        ),
        migrations.RemoveField(
            model_name='livre',
            name='note',
        ),
        migrations.RemoveField(
            model_name='livre',
            name='theme',
        ),
        migrations.AddField(
            model_name='livre',
            name='date_sortie',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='livre',
            name='auteur',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='livres', to='biblio.auteur'),
        ),
        migrations.DeleteModel(
            name='Personne',
        ),
    ]
