# Generated by Django 5.2.5 on 2025-08-26 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pizzaapp', '0002_pizza_slug_comment_ingredient'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ingredient',
            name='pizza',
        ),
        migrations.AddField(
            model_name='pizza',
            name='ingredients',
            field=models.ManyToManyField(related_name='pizza', to='pizzaapp.ingredient'),
        ),
    ]
