# Generated by Django 5.2.5 on 2025-08-26 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pizzaapp', '0003_remove_ingredient_pizza_pizza_ingredients'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pizza',
            name='ingredients',
            field=models.ManyToManyField(related_name='pizzas', to='pizzaapp.ingredient'),
        ),
    ]
